version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    # network_mode: host
    volumes:
      - ./Client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - 'node-app'

  node-app:
    image: node-app
    env_file: ./Auth/.env
    ports:
      - "8000:8000"
    networks:
      - mern-app
    volumes:
      - ./Auth/:/usr/src/app
      - /usr/src/app/node_modules
    # network_mode: host
    depends_on:
      - 'mongo'
      - 'cache-app'
    
  
  cache-app:
    image: cache-app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - 'mongo'
      - 'ingestor-app'
    # network_mode: host
    volumes:
      - ./cache/:/usr/src/app
    networks:
      - mern-app

  # cache-mongodb:
  #   image: "mongo:4.4.3"
  #   restart: always
  #   ports:
  #     - 27018:27018
  #   networks:
  #     - mern-app
      
  mongo:
    image: "mongo:4.4-bionic"
    ports:
      - "27017:27017"
    networks:
      - mern-app
    # network_mode: host
    volumes:
      - mongo-data:/data/db

  ingestor-app:
    image: ingestor-app
    restart: always
    ports:
      - 5678:5678
    hostname: data-ingestor
    container_name:  data-ingestor
    # network_mode: host
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local